ERROR - 2022-10-12 15:46:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'db-s35', 3306, '', 0)
#1 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
#6 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
#7 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\s35\vendor\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#11 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\s35\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
#5 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
#6 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#7 C:\xampp\htdocs\s35\vendor\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
#8 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#10 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\s35\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-10-12 15:46:56 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `users`.`deleted_at` IS NULL
AND `users`.`id` = :users.id:', [...], false)
 3 SYSTEMPATH\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
 5 VENDORPATH\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
 7 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
 8 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-10-12 17:54:07 --> Undefined variable: a
in APPPATH\Views\templates\topbar.php on line 19.
 1 APPPATH\Views\templates\topbar.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: a', 'APPPATH\\Views\\templates\\topbar.php', 19, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\topbar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\View\View.php(429): CodeIgniter\View\View->render('templates/topbar', null, true)
 5 APPPATH\Views\templates\index.php(41): CodeIgniter\View\View->include('templates/topbar')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\index.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('templates/index', [], true)
 9 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('user/inventaris_barang', [], true)
10 APPPATH\Controllers\Home.php(13): view('user/inventaris_barang')
11 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->inventaris()
12 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-10-12 19:33:55 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'db-s35', 3306, '', 0)
#1 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
#6 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
#7 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\s35\vendor\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#11 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\s35\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
#5 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
#6 C:\xampp\htdocs\s35\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#7 C:\xampp\htdocs\s35\vendor\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
#8 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#10 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\s35\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\s35\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-10-12 19:33:55 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `users`.`deleted_at` IS NULL
AND `users`.`id` = :users.id:', [...], false)
 3 SYSTEMPATH\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
 5 VENDORPATH\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('7')
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
 7 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(30): Myth\Auth\Authentication\LocalAuthenticator->check()
 8 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
